version: '3.5'
services:
  
  chatbot_engine:
    container_name: chatbot_engine
    restart: always
    build:
      context: ../chatbot_util
      dockerfile: ../chatbot_util/Dockerfile
    image: chatbot_engine:dev
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ../chatbot_util/:/chatbot_util/
    command: python chatbot_util/test/test.py
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
