version: '3.5'
services:
  
  chatbot_engine:
    container_name: chatbot_engine
    restart: always
    build:
      context: ../chatbot_util
      dockerfile: ../chatbot_util/Dockerfile
    image: chatbot_engine:dev
    environment:
      - PYTHONUNBUFFERED=1
      - TRANSFORMERS_CACHE=./cache/
    volumes:
      - ../chatbot_util/:/chatbot_util/
      - ~/.cache/huggingface/hub:/cache/huggingface/hub
        # command: python chatbot_util/gradio_ui.py
        # command: streamlit run streamlit_ui.py --server.port 7860
    command: python chatbot_util/function_wrapper.py
    ports:
      - 7860:7860
    networks:
      - net
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]


  chatbot_PDFs_db:
    container_name: chatbot_document_db
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      - document_data:/chroma/.chroma/index
    ports:
      - 8000:8000
    networks:
      - net

volumes:
  document_data:
    driver: local
  backups:
    driver: local

networks:
  net:
    driver: bridge
